# Generated by Django 5.0.4 on 2024-05-08 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='courses_subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
