# Generated by Django 5.0.4 on 2024-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.FileField(default='default.pdf', upload_to='media/'),
        ),
    ]
