# Generated by Django 5.0.4 on 2024-05-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='document',
            field=models.FileField(default='default.pdf', upload_to='docs/'),
        ),
    ]
