# Generated by Django 5.0.4 on 2024-05-12 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_document_alter_course_subscribers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.FileField(default='default.pdf', upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='courses_subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
